Repository woowacourse-teams/2025-hEARit, pull requests merged in 2025-07, with the labels that each got.

#3 [AN] 디자인 시스템 설정
  android/app/src/main/res/drawable/bg_gray1_radius_8dp.xml
  android/app/src/main/res/drawable/bg_purple3_radius_8dp.xml
  android/app/src/main/res/font/pretendardblack.ttf
  android/app/src/main/res/font/pretendardbold.ttf
  android/app/src/main/res/font/pretendardextrabold.ttf
  android/app/src/main/res/font/pretendardmedium.ttf
  android/app/src/main/res/font/pretendardregular.ttf
  android/app/src/main/res/font/pretendardsemibold.ttf
  android/app/src/main/res/font/promptextrabold.ttf
  android/app/src/main/res/values/colors.xml
Labels: ✨ feat, AN

#10 [BE] docker에 mysql db 설정
  backend/.gitignore
  backend/docker-compose.yml
Labels: BE, ⚙️ chore

#23 [BE] 엔티티 및 레포지토리 생성
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/common/config/JpaAuditingConfig.java
  backend/src/main/java/com/onair/hearit/domain/Bookmark.java
  backend/src/main/java/com/onair/hearit/domain/Category.java
  backend/src/main/java/com/onair/hearit/domain/Hearit.java
  backend/src/main/java/com/onair/hearit/domain/HearitKeyword.java
  backend/src/main/java/com/onair/hearit/domain/Keyword.java
  backend/src/main/java/com/onair/hearit/domain/Member.java
  backend/src/main/java/com/onair/hearit/infrastructure/BookmarkRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/CategoryRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitKeywordRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/KeywordRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/MemberRepository.java
  backend/src/main/resources/application.properties
Labels: BE, ⚙️ chore

#28 [AN] 패키지 구조화 및 하단 네비게이션 바 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/data/HearitDummyData.kt
  android/app/src/main/java/com/onair/hearit/domain/CategoryItem.kt
  android/app/src/main/java/com/onair/hearit/domain/HearitItem.kt
  android/app/src/main/java/com/onair/hearit/domain/HearitShortsItem.kt
  android/app/src/main/java/com/onair/hearit/domain/RecommendHearitItem.kt
  android/app/src/main/java/com/onair/hearit/domain/ScriptLine.kt
  android/app/src/main/java/com/onair/hearit/domain/SubtitleLine.kt
  android/app/src/main/java/com/onair/hearit/presentation/CompleteHearitActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/CreateHearitActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/DrawerClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/BaseControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailScriptAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailScriptViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ScriptAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ScriptViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendHearitAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingFragment.kt
  android/app/src/main/res/layout/activity_complete_hearit.xml
  android/app/src/main/res/layout/activity_create_hearit.xml
  android/app/src/main/res/layout/activity_player_detail.xml
  android/app/src/main/res/layout/fragment_category.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_library.xml
  android/app/src/main/res/layout/fragment_search.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/layout/item_recommend_hearit.xml
Labels: ✨ feat, AN, ⚙️ chore

#37 [AN] 안드로이드 CI 적용
  .github/workflows/android-ci.yml
  android/app/build.gradle.kts
  android/build.gradle.kts
Labels: AN, ⚙️ chore

#42 [AN] 홈 화면 추천 히어릿 carousel view 구현
  android/app/src/main/java/com/onair/hearit/data/RecommendDummyData.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/res/drawable/bg_gray1_stroke_radius_8dp.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_recommend_hearit.xml
Labels: ✨ feat, AN

#48 [AN] 탐색 화면 플레이어 수정
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ScriptAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ScriptViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/fragment_explore.xml
  android/app/src/main/res/layout/item_explore.xml
  android/app/src/main/res/layout/item_explore_script.xml
Labels: AN, 🐞 bug

#43 [BE] CI/CD 적용
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/docker-compose.yml
  backend/src/main/resources/application.properties
Labels: BE, ⚙️ chore

#51 [AN] Retrofit 기본 세팅
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/data/.gitkeep
  android/app/src/main/java/com/onair/hearit/data/dummy/BookmarkDummyData.kt
  android/app/src/main/java/com/onair/hearit/data/dummy/HearitDummyData.kt
  android/app/src/main/java/com/onair/hearit/data/dummy/RecommendDummyData.kt
  android/app/src/main/java/com/onair/hearit/di/LoggingInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/gradle/libs.versions.toml
Labels: AN, ⚙️ chore

#54 [BE] MySQL 도커 컨테이너 미실행으로 인한 CI 테스트 실패 문제 수정
  .github/workflows/backend-ci.yml
Labels: BE, 🐞 bug

#59 [BE] CI 테스트용 DB 포트 하드코딩 처리
  .github/workflows/backend-ci.yml
Labels: BE, 🐞 bug

#60 [AN] 설정 및 계정 정보 화면 디자인 변경
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingFragment.kt
  android/app/src/main/res/drawable/bg_purple1_radius_24dp.xml
  android/app/src/main/res/drawable/img_default_profile.png
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/layout_drawer.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🔨 refactor

#66 [AN] 스크롤 시 검색창 고정 기능 구현
  android/app/src/main/res/drawable/bg_gray1_radius_24dp.xml
  android/app/src/main/res/drawable/bg_gray1_radius_25dp.xml
  android/app/src/main/res/drawable/bg_gray1_radius_top_24dp.xml
  android/app/src/main/res/layout/bottom_sheet_bookmark_option.xml
  android/app/src/main/res/layout/fragment_search.xml
  android/app/src/main/res/layout/item_keyword.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#65 [AN] 북마크/로그인이 없을 때 라이브러리 화면 구현
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/app/src/main/res/drawable/bg_purple3_radius_left_8dp.xml
  android/app/src/main/res/layout/fragment_library.xml
  android/app/src/main/res/layout/item_bookmark.xml
  android/app/src/main/res/layout/layout_library_when_no_bookmark.xml
  android/app/src/main/res/layout/layout_library_when_no_login.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#68 [AN] 설정 화면 UI 테스트
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/onair/hearit/SettingFragmentTest.kt
  android/gradle/libs.versions.toml
Labels: AN, 🚧 test

#74 [BE] CI/CD 워크플로우 조건 수정
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
Labels: BE, 🐞 bug

#70 [BE] 사용자 인증, 카카오 로그인 구현
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/auth/Infrastructure/client/KakaoClientConfig.java
  backend/src/main/java/com/onair/hearit/auth/Infrastructure/client/KakaoClientProperties.java
  backend/src/main/java/com/onair/hearit/auth/Infrastructure/client/KakaoUserInfoClient.java
  backend/src/main/java/com/onair/hearit/auth/Infrastructure/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/onair/hearit/auth/Infrastructure/jwt/JwtTokenProvider.java
  backend/src/main/java/com/onair/hearit/auth/application/AuthService.java
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/dto/CurrentMember.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/KakaoLoginRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/LoginRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/SignupRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/KakaoErrorResponse.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/KakaoUserInfoResponse.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/TokenResponse.java
  backend/src/main/java/com/onair/hearit/auth/exception/KakaoClientException.java
  backend/src/main/java/com/onair/hearit/auth/exception/KakaoErrorHandler.java
  backend/src/main/java/com/onair/hearit/auth/exception/KakaoExceptionHandler.java
  backend/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/src/main/java/com/onair/hearit/domain/Member.java
  backend/src/main/java/com/onair/hearit/infrastructure/MemberRepository.java
  backend/src/main/resources/application-dev.properties
  backend/src/test/java/com/onair/hearit/IntegrationTest.java
  backend/src/test/java/com/onair/hearit/auth/Infrastructure/client/KakaoUserInfoClientTest.java
  backend/src/test/java/com/onair/hearit/auth/application/AuthKakaoServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/application/AuthServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/onair/hearit/auth/presentation/AuthKakaoLoginControllerTest.java
  backend/src/test/resources/application-fake-test.properties
  backend/src/test/resources/application-integration-test.properties
Labels: ✨ feat, BE

#79 [BE] 랜덤/추천 히어릿 리스트 조회 API
  backend/src/main/java/com/onair/hearit/application/HearitService.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/Infrastructure/client/KakaoUserInfoClientTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: ✨ feat, BE

#86 [BE] Swagger UI 설정 및 문서 기본 설명 추가
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/src/main/java/com/onair/hearit/common/config/SwaggerConfig.java
  backend/src/main/java/com/onair/hearit/presentation/FileSourceController.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/main/resources/application-dev.properties
Labels: BE, ⚙️ chore

#85 [AN] 하단 NavigationView에 재생 바 추가
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/SplashActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginActivity.kt
  android/app/src/main/res/drawable/bg_gray1_radius_top_8dp.xml
  android/app/src/main/res/drawable/check_switch_thumb.xml
  android/app/src/main/res/drawable/check_switch_track.xml
  android/app/src/main/res/drawable/ic_bottom_pause.xml
  android/app/src/main/res/drawable/ic_bottom_play.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/layout_bottom_player_controller.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/font_style.xml
Labels: ✨ feat, AN

#92 [AN] 탐색 화면 이탈 시 백그라운드 재생 오류 해결
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/res/layout/activity_splash.xml
Labels: AN, 🐞 bug

#95 [AN] 상세 재생 화면 연결
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendHearitAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendViewHolder.kt
  android/app/src/main/res/layout/fragment_explore.xml
  android/app/src/main/res/layout/item_recommend_hearit.xml
  android/app/src/main/res/layout/item_shorts.xml
Labels: ✨ feat, AN

#82 [BE] 제목 기반 히어릿 검색 기능 구현
  backend/src/main/java/com/onair/hearit/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/application/HearitService.java
  backend/src/main/java/com/onair/hearit/common/config/SwaggerConfig.java
  backend/src/main/java/com/onair/hearit/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/onair/hearit/dto/request/TitleSearchCondition.java
  backend/src/main/java/com/onair/hearit/dto/response/HearitSearchResponse.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/onair/hearit/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/dto/request/TitleSearchConditionTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: ✨ feat, BE

#99 [AN] 미디어 세션 + Notification 통한 백그라운드 재생 제어 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/gradle/libs.versions.toml
Labels: ✨ feat, AN

#105 [AN] 탐색 화면 API 연동
  android/app/src/main/java/com/onair/hearit/data/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/MediaFileRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/MediaFileRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/MediaFileRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/MediaFileService.kt
  android/app/src/main/java/com/onair/hearit/data/RandomHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/ScriptUrlResponse.kt
  android/app/src/main/java/com/onair/hearit/data/ShortAudioUrlResponse.kt
  android/app/src/main/java/com/onair/hearit/data/dummy/HearitDummyData.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/HearitShortsItem.kt
  android/app/src/main/java/com/onair/hearit/domain/RandomHearitItem.kt
  android/app/src/main/java/com/onair/hearit/domain/ShortAudioUrlItem.kt
  android/app/src/main/java/com/onair/hearit/domain/SubtitleLine.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/MediaFileRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/item_explore_script.xml
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#110 [AN] feat: 카카오 로그인 추가
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/HearitApplication.kt
  android/app/src/main/java/com/onair/hearit/data/AuthRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/AuthRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/AuthRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/AuthService.kt
  android/app/src/main/java/com/onair/hearit/data/DataStoreExt.kt
  android/app/src/main/java/com/onair/hearit/data/DataStoreRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/KakaoLoginRequest.kt
  android/app/src/main/java/com/onair/hearit/data/KakaoLoginResponse.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/DataStoreRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: ✨ feat, AN

#112 [AN] feat: 검색 화면 API 연동
  android/app/src/main/java/com/onair/hearit/data/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/SearchHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/dummy/SearchedHearitDummyData.kt
  android/app/src/main/java/com/onair/hearit/domain/SearchedHearitItem.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchedHearitAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchedHearitViewHolder.kt
  android/app/src/main/res/layout/fragment_search_result.xml
  android/app/src/main/res/layout/item_searched_hearit.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#120 [BE] fix: 개발서버 스웨거 문서에서의 CORS 문제 해결 및 문서 업데이트
  backend/src/main/java/com/onair/hearit/auth/config/CorsConfig.java
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/src/main/java/com/onair/hearit/common/config/SwaggerConfig.java
  backend/src/main/java/com/onair/hearit/presentation/BookmarkController.java
Labels: BE, 🐞 bug, 📄 docs

#127 [AN] feat: 탐색 화면 API 업데이트 대응
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/MediaFileRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RandomHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/model/ShortsHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/MediaFileRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetShortsHearitUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#128 [BE] feat: 로그인한 사용자 정보 조회 API 기능 및 SecurityConfig 리팩터링
  backend/src/main/java/com/onair/hearit/application/BookmarkService.java
  backend/src/main/java/com/onair/hearit/application/KeywordService.java
  backend/src/main/java/com/onair/hearit/application/MemberService.java
  backend/src/main/java/com/onair/hearit/auth/application/AuthService.java
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/KakaoUserInfoResponse.java
  backend/src/main/java/com/onair/hearit/auth/infrastructure/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/src/main/java/com/onair/hearit/domain/Member.java
  backend/src/main/java/com/onair/hearit/dto/response/KeywordResponse.java
  backend/src/main/java/com/onair/hearit/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/onair/hearit/presentation/BookmarkController.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/main/java/com/onair/hearit/presentation/KeywordController.java
  backend/src/main/java/com/onair/hearit/presentation/MemberController.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/static/images/default-profile.jpg
  backend/src/test/java/com/onair/TestFixture.java
  backend/src/test/java/com/onair/hearit/application/BookmarkServiceTest.java
  backend/src/test/java/com/onair/hearit/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/application/KeywordServiceTest.java
  backend/src/test/java/com/onair/hearit/application/MemberServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/application/AuthKakaoServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/application/AuthServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/KeywordControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/MemberControllerTest.java
  backend/src/test/resources/application-fake-test.properties
  backend/src/test/resources/application-integration-test.properties
Labels: ✨ feat, BE

#130 [AN] feat: 최근 들은 히어릿 저장, 조회
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/HearitApplication.kt
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDao.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDatabase.kt
  android/app/src/main/java/com/onair/hearit/data/database/RecentHearitEntity.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/CategoryRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/CategoryRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/CategoryRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/RecentHearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/DatabaseProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RecentHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/RecentHearitRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchViewModelFactory.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_recommend_hearit.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: ✨ feat, AN

#137 [BE] fix: admin 관련 api에서 401예외 터지는 문제 해결 #136
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
Labels: BE, 🐞 bug

#133 [BE] refactor: 히어릿 검색 기능 통합 및 카테고리 URI 개선
  backend/src/main/java/com/onair/hearit/application/CategoryService.java
  backend/src/main/java/com/onair/hearit/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/auth/config/SecurityConfig.java
  backend/src/main/java/com/onair/hearit/dto/request/CategorySearchCondition.java
  backend/src/main/java/com/onair/hearit/dto/request/KeywordSearchCondition.java
  backend/src/main/java/com/onair/hearit/dto/request/TitleSearchCondition.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/presentation/CategoryController.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/application/CategoryServiceTest.java
  backend/src/test/java/com/onair/hearit/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/dto/request/TitleSearchConditionTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/CategoryControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: BE, 🔨 refactor

#140 feat: 코드래빗 설정 파일 적용
  .coderabbit.yaml
Labels: ⚙️ chore

#142 [BE] refactor: 히어릿 검색 및 카테고리 조회 응답을 PagedResponse로 리팩터링 #141
  backend/src/main/java/com/onair/hearit/application/CategoryService.java
  backend/src/main/java/com/onair/hearit/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/presentation/CategoryController.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/application/CategoryServiceTest.java
  backend/src/test/java/com/onair/hearit/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/CategoryControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: BE, 🔨 refactor

#144 [AN] feat: 사용자 정보 조회 api 연결
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/api/MemberService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/MemberRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/MemberRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/dto/UserInfoResponse.kt
  android/app/src/main/java/com/onair/hearit/data/repository/DataStoreRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/MemberRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/LoggingInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/UserNotRegisteredException.kt
  android/app/src/main/java/com/onair/hearit/domain/model/UserInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/DataStoreRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/MemberRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/BookmarkUiState.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/BookmarkViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/BookmarkViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModelFactory.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_library.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/layout_library_when_no_bookmark.xml
  android/app/src/main/res/layout/layout_library_when_no_login.xml
  android/app/src/main/res/raw/test_audio.mp3
  android/app/src/main/res/raw/test_audio2.mp3
  android/app/src/main/res/raw/test_audio3.mp3
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: ✨ feat, AN

#150 [AN] feat: 검색 화면 API 대응
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/dto/SearchHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/repository/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/model/PageResult.kt
  android/app/src/main/java/com/onair/hearit/domain/model/Paging.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/CategoryClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultViewModel.kt
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/layout/item_keyword.xml
Labels: ✨ feat, AN

#155 [AN] refactor: 탐색화면 API 페이지네이션 적용
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/dto/RandomHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/repository/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RandomHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/res/layout/item_explore_script.xml
  android/app/src/main/res/layout/item_shorts.xml
Labels: AN, 🔨 refactor

#159 [BE] fix: 백엔드 브랜치에 코드 래빗 설정 파일 추가 #157
  .coderabbit.yaml
Labels: BE, 🐞 bug, ⚙️ chore

#158 fix: 코드래빗 설정 파일 제거 #154
  .coderabbit.yaml
Labels: 🐞 bug, ⚙️ chore

#165 [AN] refactor: 최근 들은 히어릿 조회, 저장 변경
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecentHearitClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultFragment.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_search_result.xml
  android/app/src/main/res/layout/item_searched_hearit.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🔨 refactor

#174 [AN] fix: 코드 래빗 설정 파일 수정 #173
  .coderabbit.yaml
Labels: AN, 🐞 bug, ⚙️ chore

#178 [AN] fix: 카테고리 조회 기능 수정
  android/app/src/main/java/com/onair/hearit/data/api/CategoryService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/CategoryRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/CategoryRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/CategoryRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/SearchInput.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/CategoryRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetSearchResultUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/CategoryClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchResultViewModelFactory.kt
  android/app/src/main/res/layout/item_category.xml
Labels: AN, 🐞 bug

#182 [AN] bug: 로그인 안 했을 때 탐색/상세 재생 화면이 안 보이는 문제 수정
  android/app/src/main/java/com/onair/hearit/data/api/BookmarkService.kt
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/api/MemberService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/BookmarkRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/BookmarkRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/MemberRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/NoBookmarkException.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/BookmarkRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryViewModel.kt
Labels: AN, 🐞 bug

#187 [BE] chore: CI 환경 변수 secrets으로 변경 #186
  .github/workflows/backend-ci.yml
  backend/src/test/java/com/onair/hearit/presentation/CategoryControllerTest.java
Labels: BE, ⚙️ chore

#207 [BE] feat: 관리자 인증 구현 #146
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/admin/application/AdminAuthService.java
  backend/src/main/java/com/onair/hearit/admin/application/AdminCategoryService.java
  backend/src/main/java/com/onair/hearit/admin/application/AdminKeywordService.java
  backend/src/main/java/com/onair/hearit/admin/domain/Admin.java
  backend/src/main/java/com/onair/hearit/admin/domain/AdminUserDetails.java
  backend/src/main/java/com/onair/hearit/admin/domain/Password.java
  backend/src/main/java/com/onair/hearit/admin/dto/request/AdminLoginRequest.java
  backend/src/main/java/com/onair/hearit/admin/infrastructure/AdminRepository.java
  backend/src/main/java/com/onair/hearit/admin/presentation/AdminCategoryController.java
  backend/src/main/java/com/onair/hearit/admin/presentation/AdminHearitController.java
  backend/src/main/java/com/onair/hearit/admin/presentation/AdminKeywordController.java
  backend/src/main/java/com/onair/hearit/admin/presentation/AdminViewController.java
  backend/src/main/java/com/onair/hearit/auth/application/AdminUserDetailsService.java
  backend/src/main/java/com/onair/hearit/auth/config/AdminSecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/infrastructure/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/onair/hearit/common/exception/GlobalExceptionHandler.java
  backend/src/main/resources/static/favicon.ico
  backend/src/main/resources/templates/admin/category-list.html
  backend/src/main/resources/templates/admin/hearit-list.html
  backend/src/main/resources/templates/admin/home.html
  backend/src/main/resources/templates/admin/keyword-list.html
  backend/src/main/resources/templates/admin/login.html
  backend/src/main/resources/templates/admin/navbar.html
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminCategoryControllerTest.java
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminHearitControllerTest.java
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminKeywordControllerTest.java
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminSecurityTestHelper.java
  backend/src/test/java/com/onair/hearit/auth/config/AdminSecurityConfigTest.java
  backend/src/test/java/com/onair/hearit/auth/config/ApiSecurityConfigTest.java
  backend/src/test/java/com/onair/hearit/fixture/DbHelper.java
  backend/src/test/java/com/onair/hearit/fixture/IntegrationTest.java
  backend/src/test/resources/dbclean.sql
Labels: ✨ feat, BE

#214 [BE] refactor: RecommendHearitResponse 반환 필드 변경 #211
  backend/src/main/java/com/onair/hearit/dto/response/RecommendHearitResponse.java
Labels: BE, 🔨 refactor

#220 [AN] feat: 검색 화면 최근 검색어 view 추가
  android/app/src/main/java/com/onair/hearit/data/KeywordMapper.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDao.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDatabase.kt
  android/app/src/main/java/com/onair/hearit/data/database/SearchHistoryEntity.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/RecentKeywordRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RecentSearch.kt
  android/app/src/main/java/com/onair/hearit/domain/model/SearchInput.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/RecentKeywordRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetSearchResultUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/KeywordViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/CategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/CategoryViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/SearchCategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/RecentSearchAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/RecentSearchClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/RecentSearchViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/SearchRecentFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchResultClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchResultFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchResultViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchResultViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchedHearitAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchedHearitViewHolder.kt
  android/app/src/main/res/drawable/ic_recent_keyword.xml
  android/app/src/main/res/drawable/ic_time.xml
  android/app/src/main/res/layout/fragment_search.xml
  android/app/src/main/res/layout/fragment_search_category.xml
  android/app/src/main/res/layout/fragment_search_recent.xml
  android/app/src/main/res/layout/fragment_search_result.xml
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/layout/item_keyword.xml
  android/app/src/main/res/layout/item_recent_keyword.xml
  android/app/src/main/res/layout/item_searched_hearit.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#210 [AN] feat: 하단 재생바에 히어릿 정보 반영 및 재생 연동 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/PlaybackInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlayerControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlayerViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlayerViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/BaseControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/script/ScriptFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/res/drawable/ic_mini_notification.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/layout_bottom_player_controller.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN
