Repository woowacourse-teams/2025-hEARit, pull requests merged in 2025-09, with the labels that each got.

#492 [AN] feat: 비회원 GUID API 요청 시 헤더에 추가
  android/app/src/main/java/com/onair/hearit/data/DataStoreExt.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/di/TokenInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginActivity.kt
  android/app/src/main/res/layout/item_searched_hearit.xml
Labels: ✨ feat, AN

#497 [AN] refactor: 하단 재생바 Runnable 코드 개선
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
Labels: AN, 🔨 refactor

#488 [BE] feat: 사용자 재생기록 저장 및 조회 #487
  backend/src/main/java/com/onair/hearit/app/application/BookmarkService.java
  backend/src/main/java/com/onair/hearit/app/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/app/application/HearitService.java
  backend/src/main/java/com/onair/hearit/app/application/PlayingHistoryService.java
  backend/src/main/java/com/onair/hearit/app/dto/request/PlayingHistoryRequest.java
  backend/src/main/java/com/onair/hearit/app/dto/response/BookmarkHearitResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitDetailResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitOfCategoryResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitSearchResponse.java
  backend/src/main/java/com/onair/hearit/app/infrastructure/scheduler/PlayingHistoryBuffer.java
  backend/src/main/java/com/onair/hearit/app/infrastructure/scheduler/SchedulerConfig.java
  backend/src/main/java/com/onair/hearit/app/presentation/HearitController.java
  backend/src/main/java/com/onair/hearit/app/presentation/PlayingHistoryController.java
  backend/src/main/java/com/onair/hearit/common/domain/PlayingHistory.java
  backend/src/main/java/com/onair/hearit/common/exception/ErrorCode.java
  backend/src/main/java/com/onair/hearit/common/exception/custom/BufferRequestException.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/dto/BookmarkWithPlaytimeProjection.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/dto/HearitWithPlayTimeProjection.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jdbc/PlayingHistoryCommandRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/BookmarkRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/HearitRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/PlayingHistoryRepository.java
  backend/src/main/resources/db/migration/V202509071351__playing_history.sql
  backend/src/main/resources/db/migration/V202509081624__last_play_time_to_long.sql
  backend/src/test/java/com/onair/hearit/app/application/BookmarkServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/PlayingHistoryServiceTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/PlayingHistoryControllerTest.java
  backend/src/test/java/com/onair/hearit/common/domain/PlayingHistoryTest.java
  backend/src/test/java/com/onair/hearit/common/infrastructure/jpa/BookmarkRepositoryTest.java
  backend/src/test/java/com/onair/hearit/common/infrastructure/jpa/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/fixture/DbHelper.java
  backend/src/test/resources/dbclean.sql
Labels: ✨ feat, BE

#515 [BE] fix: explore_score uk 추가 (#514)
  backend/src/main/resources/db/migration/V2025090151046__explore_score_uk.sql
Labels: BE, 🐞 bug

#520 [AN] feat: 탐색화면 CursorID API 업데이트 대응
  android/app/src/main/java/com/onair/hearit/data/dto/RandomHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/CursorInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/model/CursorResult.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RandomHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/model/ShortsHearit.kt
  android/app/src/main/java/com/onair/hearit/presentation/DetailResult.kt
  android/app/src/main/java/com/onair/hearit/presentation/Extensions.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/test/java/com/onair/hearit/HearitFixtures.kt
Labels: ✨ feat, AN

#518 [AN] refactor: 상세화면 리팩터링
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/BaseControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/res/drawable/img_player_detail_thumbnail.png
  android/app/src/main/res/layout/activity_player_detail.xml
  android/app/src/main/res/layout/item_playlist.xml
  android/app/src/main/res/layout/layout_player_detail_thumbnail.xml
Labels: AN, 🔨 refactor

#522 [AN] feat: 재생 기록 저장 및 상세 화면 재생 기록부터 재생
  android/app/src/main/java/com/onair/hearit/data/api/PlayingHistoryService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/PlayingHistoryDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/PlayingHistoryDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/dto/PlayingHistoryRequest.kt
  android/app/src/main/java/com/onair/hearit/data/repository/PlayingHistoryRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/DataSourceProvider.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/di/RepositoryProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/PlayingHistoryRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackHistoryListener.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
Labels: ✨ feat, AN

#537 [BE] feat: 탐색 API에서 구버전 호환 가능하도록 버저닝 추가
  backend/src/main/java/com/onair/hearit/app/dto/response/CursorResponseV1.java
  backend/src/main/java/com/onair/hearit/app/presentation/HearitController.java
  backend/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/java/com/onair/hearit/docs/ApiDocSnippets.java
Labels: ✨ feat, BE

#534 [AN] bug: 탐색 화면 재생바 클릭/다음 아이템 재생 오류 수정
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/MainActivity.kt
Labels: AN, ⛔️ hotfix

#550 [BE] fix: flyway의 v1 파일 수정 #548
  backend/src/main/resources/db/migration/V1__init.sql
Labels: BE, 🐞 bug

#561 [BE] fix: 히어릿 총 재생 시간에 패딩 1초 추가 #560
  backend/src/main/java/com/onair/hearit/common/domain/PlayingHistory.java
  backend/src/test/java/com/onair/hearit/common/domain/PlayingHistoryTest.java
Labels: BE, 🐞 bug

#570 [AN] fix: 검색 화면 버그 수정
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/SearchRecentFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/recentSearch/RecentSearchPageFragment.kt
  android/app/src/main/res/drawable/bg_circle.xml
  android/app/src/main/res/drawable/bg_gradient_black_gray_radius_8dp.xml
  android/app/src/main/res/drawable/bg_gray1_radius_top_8dp.xml
  android/app/src/main/res/drawable/bg_gray4_radius_8dp.xml
  android/app/src/main/res/drawable/bg_purple3_radius_left_8dp.xml
  android/app/src/main/res/layout/fragment_category.xml
  android/app/src/main/res/layout/item_bookmark.xml
  android/app/src/main/res/layout/item_category_hearit.xml
  android/app/src/main/res/layout/item_grouped_category.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🐞 bug

#597 [BE] feat: 히어릿 상세조회 lastPlayTime 초기화 규칙 적용 및 검색 응답에 정보 추가
  backend/src/main/java/com/onair/hearit/app/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/app/application/HearitService.java
  backend/src/main/java/com/onair/hearit/app/application/PlayingHistoryService.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitSearchResponse.java
  backend/src/main/java/com/onair/hearit/app/presentation/PlayingHistoryController.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/HearitRepository.java
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminHearitControllerTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/PlayingHistoryServiceTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/PlayingHistoryControllerTest.java
Labels: ✨ feat, BE

#589 [AN] refactor: 재생 기록 추가 #582
  android/app/src/main/java/com/onair/hearit/data/dto/BookmarkResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/BookmarkMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/Bookmark.kt
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackHistoryListener.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackSessionCallback.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackStateSaver.kt
  android/app/src/main/res/drawable/ic_hearit_finished.xml
  android/app/src/main/res/layout/fragment_explore.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_bookmark.xml
  android/app/src/main/res/layout/layout_drawer.xml
Labels: AN, 🔨 refactor

#592 [AN] feat: 북마크들을 재생한 기록부터 재생하는 기능 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/data/dto/BookmarkResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/BookmarkMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/Bookmark.kt
  android/app/src/main/java/com/onair/hearit/domain/model/PlaybackInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RecentHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/service/LibraryPlaybackHandler.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackMediaItemManager.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackPositionListener.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackSessionCallback.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackStateSaver.kt
  android/app/src/main/java/com/onair/hearit/service/RecentPlaybackHandler.kt
  android/app/src/main/java/com/onair/hearit/service/model/LibraryLoadResult.kt
  android/app/whatsnew/whatsnew-ko-KR
Labels: ✨ feat, AN

#602 [BE] chore: bump version to 1.2.2 #601
  backend/build.gradle
Labels: BE, ⚙️ chore

#603 [BE] release: 1.2.2
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/admin/presentation/view/AdminViewController.java
  backend/src/main/java/com/onair/hearit/app/application/BookmarkService.java
  backend/src/main/java/com/onair/hearit/app/application/CategoryService.java
  backend/src/main/java/com/onair/hearit/app/application/HearitSearchService.java
  backend/src/main/java/com/onair/hearit/app/application/HearitService.java
  backend/src/main/java/com/onair/hearit/app/application/KeywordService.java
  backend/src/main/java/com/onair/hearit/app/application/MemberService.java
  backend/src/main/java/com/onair/hearit/app/application/PlayingHistoryService.java
  backend/src/main/java/com/onair/hearit/app/dto/response/BookmarkHearitResponseV2.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitSearchResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/RecentlyPlayedHearitResponse.java
  backend/src/main/java/com/onair/hearit/app/infrastructure/scheduler/PlayingHistoryBuffer.java
  backend/src/main/java/com/onair/hearit/app/presentation/PlayingHistoryController.java
  backend/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/dto/BookmarkWithPlayingHistoryProjection.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/dto/BookmarkWithPlaytimeProjection.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jdbc/PlayingHistoryCommandRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/BookmarkRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/HearitRepository.java
  backend/src/main/java/com/onair/hearit/common/infrastructure/jpa/PlayingHistoryRepository.java
  backend/src/main/resources/db/migration/V2025090222217__playing_history_index.sql
  backend/src/main/resources/static/favicon.ico
  backend/src/main/resources/templates/admin/home.html
  backend/src/main/resources/templates/admin/navbar.html
  backend/src/main/resources/templates/admin/trace.html
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminHearitControllerTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/app/application/PlayingHistoryServiceTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/PlayingHistoryControllerTest.java
  backend/src/test/java/com/onair/hearit/common/infrastructure/jpa/BookmarkRepositoryTest.java
  backend/src/test/java/com/onair/hearit/common/infrastructure/jpa/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/common/infrastructure/jpa/PlayingHistoryRepositoryTest.java
Labels: BE, ⚙️ chore

#612 [BE] fix: SecurityFilterChain Order 고정되도록 조정 추가 #611
  backend/admin/src/main/java/com/onair/hearit/auth/config/AdminSecurityConfig.java
  backend/app/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
Labels: BE, 🐞 bug

#619 [BE] RestDocs 문서화를 모킹으로 변경하여 문서화 환경 독립화 #598
  backend/app/build.gradle
  backend/app/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/app/src/main/java/com/onair/hearit/playinghistory/dto/RecentlyPlayedHearitResponse.java
  backend/app/src/test/java/com/onair/hearit/auth/presentation/AuthControllerTest.java
  backend/app/src/test/java/com/onair/hearit/auth/presentation/AuthIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/auth/presentation/AuthKakaoLoginIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/bookmark/presentation/BookmarkControllerTest.java
  backend/app/src/test/java/com/onair/hearit/bookmark/presentation/BookmarkIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/category/presentation/CategoryControllerTest.java
  backend/app/src/test/java/com/onair/hearit/category/presentation/CategoryIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/explore/presentation/ExploreControllerTest.java
  backend/app/src/test/java/com/onair/hearit/explore/presentation/ExploreIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/fixture/ApiDocSnippets.java
  backend/app/src/test/java/com/onair/hearit/fixture/ControllerTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/FileSourceControllerTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/FileSourceIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/HearitControllerTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/HearitIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/HearitSearchControllerTest.java
  backend/app/src/test/java/com/onair/hearit/hearit/presentation/HearitSearchIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/keyword/presentation/KeywordControllerTest.java
  backend/app/src/test/java/com/onair/hearit/keyword/presentation/KeywordIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/member/presentation/MemberControllerTest.java
  backend/app/src/test/java/com/onair/hearit/member/presentation/MemberIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/playinghistory/presentation/PlayingHistoryControllerTest.java
  backend/app/src/test/java/com/onair/hearit/playinghistory/presentation/PlayingHistoryIntegrationTest.java
  backend/app/src/test/java/com/onair/hearit/recommendhearit/presentation/RecommendHearitControllerTest.java
  backend/app/src/test/java/com/onair/hearit/recommendhearit/presentation/RecommendHearitIntegrationTest.java
  backend/core/src/testFixtures/java/com/onair/hearit/core/fixture/ApiTest.java
Labels: BE, 🔨 refactor
