Repository woowacourse-teams/2025-hEARit, pull requests merged in 2025-10, with the labels that each got.

#620 [AN] refactor: 재생목록 상세화면으로 이동하는 기능 구현
  android/app/src/main/java/com/onair/hearit/presentation/detail/script/ScriptAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/playlist/PlaylistAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/playlist/PlaylistBottomSheet.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/playlist/PlaylistClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/playlist/PlaylistViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/main/playlist/PlaylistViewModel.kt
  android/app/src/main/res/layout/item_playlist.xml
Labels: AN, 🔨 refactor

#640 [BE] refactor: batch Insert 설정 파일 수정 #638
  backend/boot/src/main/resources/application-dev.properties
  backend/core/src/main/java/com/onair/hearit/core/infrastructure/jdbc/ExploreScoreCommandRepository.java
  backend/core/src/main/java/com/onair/hearit/core/infrastructure/jdbc/PlayingHistoryCommandRepository.java
  backend/core/src/testFixtures/resources/application-integration-test.properties
Labels: BE, 🔨 refactor

#615 [BE] refactor : 히어릿 탐색 테스트 작성 및 리팩토링
  backend/app/src/main/java/com/onair/hearit/app/explore/application/ExploreScoreInitializer.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/HearitExploreService.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scorefactor/DefaultRandomNumberGenerator.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scorefactor/RandomNumberGenerator.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scorefactor/RandomScoreFactor.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scorefactor/RecencyScoreFactor.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scoreprocessor/AbstractExploreScoreProcessor.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scoreprocessor/ExploreScoreProcessor.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scoreprocessor/GuestExploreScoreProcessor.java
  backend/app/src/main/java/com/onair/hearit/app/explore/application/scoreprocessor/MemberExploreScoreProcessor.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/ExploreScoreCalculatorTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/ExploreScoreInitializerTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/HearitExploreServiceTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/scorefactor/BookmarkScoreFactorTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/scorefactor/RandomScoreFactorTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/scorefactor/RecencyScoreFactorTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/scoreprocessor/GuestExploreScoreProcessorTest.java
  backend/app/src/test/java/com/onair/hearit/app/explore/application/scoreprocessor/MemberExploreScoreProcessorTest.java
  backend/app/src/test/java/com/onair/hearit/app/fixture/DbHelper.java
  backend/core/src/main/java/com/onair/hearit/core/domain/Hearit.java
  backend/core/src/testFixtures/java/com/onair/hearit/common/TestClock.java
  backend/core/src/testFixtures/java/com/onair/hearit/core/fixture/TestJpaAuditingConfig.java
Labels: BE, 🔨 refactor

#635 [BE] feat: 최근 업로드된 히어릿 조회 API
  backend/app/src/main/java/com/onair/hearit/app/common/config/ConverterConfig.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/application/HearitService.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/HearitOverviewResponse.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/HearitSortRequest.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/RecentHearitResponse.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/converter/HearitSortRequestConverter.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/param/HearitSortField.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/dto/param/SortDirection.java
  backend/app/src/main/java/com/onair/hearit/app/hearit/presentation/HearitController.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/application/HearitServiceTest.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/dto/converter/HearitSortRequestConverterTest.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/dto/param/HearitSortFieldTest.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/dto/param/SortDirectionTest.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/presentation/HearitControllerTest.java
  backend/app/src/test/java/com/onair/hearit/app/hearit/presentation/HearitIntegrationTest.java
  backend/core/src/main/java/com/onair/hearit/core/infrastructure/jpa/HearitRepository.java
  backend/core/src/test/java/com/onair/hearit/core/infrastructure/jpa/HearitRepositoryTest.java
Labels: ✨ feat, BE

#649 [BE] chore: Loki 도입을 위한 Log4j2 설정 변경 #648
  backend/boot/src/main/resources/application-dev.properties
  backend/core/src/main/java/com/onair/hearit/core/log/LoggingAspect.java
  backend/core/src/main/resources/log4j2/log4j2.xml
Labels: BE, ⚙️ chore
