Repository woowacourse-teams/2025-hEARit, pull requests merged in 2025-08, with the labels that each got.

#232 [AN] refactor: 홈 화면 디자인 변경
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryItemAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CategoryItemViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/GroupedCategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/GroupedCategoryViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_category_hearit.xml
Labels: AN, ⛔️ hotfix

#238 [BE] chore: 개발환경과 운영환경 ci,cd 분리 #237
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-dev-ci.yml
  .github/workflows/backend-prod-cd.yml
  .github/workflows/backend-prod-ci.yml
  backend/build.gradle
Labels: BE, ⚙️ chore

#230 [BE] feat: logging 추가 #204
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/infrastructure/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/onair/hearit/common/config/LogConfig.java
  backend/src/main/java/com/onair/hearit/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/onair/hearit/common/log/FilterErrorLogger.java
  backend/src/main/java/com/onair/hearit/common/log/LoggingAspect.java
  backend/src/main/java/com/onair/hearit/common/log/message/JsonMaskingPrettyFormatter.java
  backend/src/main/java/com/onair/hearit/common/log/message/dto/ExceptionLog.java
  backend/src/main/java/com/onair/hearit/common/log/message/dto/RequestInfo.java
  backend/src/main/java/com/onair/hearit/common/log/message/dto/RequestLog.java
  backend/src/main/java/com/onair/hearit/common/log/message/dto/ResponseLog.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/log4j2/log4j2.xml
Labels: ✨ feat, BE

#234 [AN] feat: 홈 화면에서 다른 화면으로 이동 기능 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/data/database/HearitDatabase.kt
  android/app/src/main/java/com/onair/hearit/domain/model/Direction.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RecommendHearits.kt
  android/app/src/main/java/com/onair/hearit/domain/model/SearchInput.kt
  android/app/src/main/java/com/onair/hearit/presentation/Extensions.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/GroupedCategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/GroupedCategoryViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HorizontalMarginItemDecoration.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/NavigateViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/RecommendHearitAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/CategoryClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/CategoryAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/CategoryViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/SearchCategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/SearchRecentFragment.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/layout/item_category_hearit.xml
  android/app/src/main/res/layout/item_grouped_category.xml
  android/app/src/main/res/layout/item_navigate.xml
  android/app/src/main/res/layout/layout_drawer.xml
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
Labels: ✨ feat, AN

#242 [AN] bug: 북마크 시 오디오 초기화되는 문제 수정 #226
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/onair/hearit/presentation/CompleteHearitActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/CreateHearitActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/activity_complete_hearit.xml
  android/app/src/main/res/layout/activity_create_hearit.xml
  android/app/src/main/res/layout/activity_player_detail.xml
  android/app/src/main/res/layout/item_shorts.xml
Labels: AN, 🐞 bug

#243 [AN] feat: 히어릿 이어서 재생 기능 구현 #221
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/HearitApplication.kt
  android/app/src/main/java/com/onair/hearit/data/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDao.kt
  android/app/src/main/java/com/onair/hearit/data/database/HearitDatabase.kt
  android/app/src/main/java/com/onair/hearit/data/database/RecentHearitEntity.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/HearitLocalDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/RecentHearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/ServiceProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/PlaybackInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RecentHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/RecentHearitRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlaybackPositionSaver.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlaybackStarter.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlayerViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlayerViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/BaseControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/explore_player_controller.xml
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/main/res/layout/layout_bottom_player_controller.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: ✨ feat, AN

#256 [BE] fix: Refresh api 누락된 문서 추가 #255
  backend/src/test/java/com/onair/hearit/auth/presentation/AuthControllerTest.java
Labels: BE, 🐞 bug, 📄 docs

#270 [BE] fix: Jwt Filter에서 화이트리스트API여도 token이 비어있는 경우에만 통과하도록 수정 #269
  backend/src/main/java/com/onair/hearit/auth/infrastructure/jwt/JwtAuthenticationFilter.java
Labels: BE, 🐞 bug

#268 [BE] fix: 상세 조회 비로그인, 로그인 문서 오류 수정 #262
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/presentation/CategoryControllerTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: BE

#257 [AN] refactor: 마지막 재생 위치 저장 로직을 Service로 이동
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/PlaybackPositionSaver.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/BaseControllerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/service/NotificationManager.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackMediaItemManager.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackSessionCallback.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackStateSaver.kt
  android/app/src/main/res/xml/network_security_config.xml
Labels: AN, 🔨 refactor

#267 [AN] feat: 탐색 화면 디자인 수정 및 API 대응
  android/app/src/main/java/com/onair/hearit/data/dto/RandomHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/RandomHearit.kt
  android/app/src/main/java/com/onair/hearit/domain/model/ShortsHearit.kt
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/drawable/img_explore_lp.png
  android/app/src/main/res/layout/fragment_explore.xml
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#280 [BE] feat: 회원 탈퇴 기능 추가 #275
  backend/src/main/java/com/onair/hearit/auth/application/AuthService.java
  backend/src/main/java/com/onair/hearit/auth/presentation/AuthController.java
  backend/src/main/java/com/onair/hearit/common/log/message/JsonMaskingPrettyFormatter.java
  backend/src/main/java/com/onair/hearit/domain/Member.java
  backend/src/main/java/com/onair/hearit/infrastructure/MemberRepository.java
  backend/src/test/java/com/onair/hearit/auth/application/AuthServiceTest.java
  backend/src/test/java/com/onair/hearit/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/MemberRepositoryTest.java
Labels: ✨ feat, BE

#292 [AN] feat: 오디오 알림을 누르면 상세 화면으로 이동 기능 구현
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/ObserveOnce.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
Labels: ✨ feat, AN

#286 [BE] feat : 사용자 북마크 기반 상위 카테고리 제공 #283
  backend/src/main/java/com/onair/hearit/application/HearitService.java
  backend/src/main/java/com/onair/hearit/dto/response/GroupedHearitsWithCategoryResponse.java
  backend/src/main/java/com/onair/hearit/dto/response/HearitsWithRecommendCategoryResponse.java
  backend/src/main/java/com/onair/hearit/infrastructure/CategoryRepository.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/CategoryRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: ✨ feat, BE

#289 [BE] feat: 출처에 링크 추가 #273
  backend/.editorconfig
  backend/src/main/java/com/onair/hearit/admin/application/AdminHearitService.java
  backend/src/main/java/com/onair/hearit/admin/dto/request/HearitCreateRequest.java
  backend/src/main/java/com/onair/hearit/admin/dto/request/HearitMetaDataUpdateRequest.java
  backend/src/main/java/com/onair/hearit/admin/dto/response/HearitAdminResponse.java
  backend/src/main/java/com/onair/hearit/domain/Hearit.java
  backend/src/main/java/com/onair/hearit/domain/Source.java
  backend/src/main/java/com/onair/hearit/dto/response/HearitDetailResponse.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/templates/admin/hearit-create.html
  backend/src/main/resources/templates/admin/hearit-list.html
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminHearitControllerTest.java
  backend/src/test/java/com/onair/hearit/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/domain/HearitTest.java
  backend/src/test/java/com/onair/hearit/domain/SourceTest.java
  backend/src/test/java/com/onair/hearit/fixture/TestFixture.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
  backend/src/test/resources/dbclean.sql
Labels: ✨ feat, BE

#309 [AN] feat: 탐색 화면 알고리즘 개선으로 인한 API 변경 대응
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/dto/RandomHearitResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/HearitMapper.kt
  android/app/src/main/java/com/onair/hearit/data/repository/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/MediaFileRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/domain/model/CursorInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/model/CursorResult.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/test/java/com/onair/hearit/HearitFixtures.kt
Labels: ✨ feat, AN

#316 [BE] Merge branch 'develop-be' into develop
  backend/src/main/java/com/onair/hearit/common/exception/ErrorCode.java
  backend/src/main/java/com/onair/hearit/common/exception/GlobalExceptionHandler.java
Labels: BE

#317 [AN] hotfix: android-ci keystore 추가
  .github/workflows/android-ci.yml
Labels: AN, ⚙️ chore

#319 [AN] chore: keystore ci 수정
  .github/workflows/android-ci.yml
Labels: ⚙️ chore

#345 [BE] chore: Spring Boot Actuator 활성화 #344
  backend/build.gradle
  backend/src/main/resources/application.properties
Labels: ✨ feat, BE

#343 [AN] refactor: 토큰 interceptor에서 넣도록 수정
  android/app/src/main/java/com/onair/hearit/data/api/BookmarkService.kt
  android/app/src/main/java/com/onair/hearit/data/api/HearitService.kt
  android/app/src/main/java/com/onair/hearit/data/api/MediaFileService.kt
  android/app/src/main/java/com/onair/hearit/data/api/MemberService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/BookmarkRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/BookmarkRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/HearitRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/HearitRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/MemberRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/MemberRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/HearitRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/MemberRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/NetworkProvider.kt
  android/app/src/main/java/com/onair/hearit/di/TokenInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/di/UseCaseProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/BookmarkRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/HearitRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/MemberRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetHearitUseCase.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModel.kt
  android/app/src/test/java/com/onair/hearit/HearitRepositoryImplTest.kt
Labels: AN, 🔨 refactor

#350 [AN] refactor: 탐색화면, 하단 재생바 피드백 반영
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/presentation/BindingAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/explore_player_controller.xml
  android/app/src/main/res/layout/fragment_explore.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_explore_skeleton.xml
  android/app/src/main/res/layout/item_home_skeleton.xml
  android/app/src/main/res/layout/item_shorts.xml
  android/app/src/main/res/layout/layout_bottom_player_controller.xml
  android/app/src/main/res/values/colors.xml
  android/gradle/libs.versions.toml
Labels: AN, 🔨 refactor

#351 [AN] refactor: 3차 데모데이 QA 반영
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/HearitApplication.kt
  android/app/src/main/java/com/onair/hearit/data/api/AuthService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/PreferencesLocalDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/local/PreferencesLocalDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/AuthRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/AuthRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/BookmarkRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/MemberRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/DataSourceProvider.kt
  android/app/src/main/java/com/onair/hearit/di/RepositoryProvider.kt
  android/app/src/main/java/com/onair/hearit/di/TokenInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetHearitUseCase.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/Extensions.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModelFactory.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModelFactory.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/item_keyword.xml
  android/app/whatsnew/whatsnew-ko-KR
  android/app/whatsnew/whatsnew-ko-KR.txt
Labels: AN, 🔨 refactor

#361 [AN] bug: 하단 재생바 및 서비스 관련 오류 수정
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackStateSaver.kt
  android/app/src/main/java/com/onair/hearit/service/PlayerNotificationManager.kt
  android/app/src/main/res/layout/item_home_skeleton.xml
Labels: AN, 🐞 bug

#363 [AN] feat: 스크립트 클릭 시 재생 위치 이동 기능 구현
  android/app/src/main/java/com/onair/hearit/presentation/detail/script/ScriptAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/script/ScriptFragment.kt
Labels: ✨ feat, AN

#364 [AN] feat: 인앱 업데이트 기능 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/di/DataSourceProvider.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/CenterScrollListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashActivity.kt
  android/gradle/libs.versions.toml
Labels: ✨ feat, AN

#367 [AN] feat: 네트워크 연결 관리 기능 구현
  android/app/src/main/java/com/onair/hearit/data/datasource/ErrorResponseHandler.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/NetworkResult.kt
  android/app/src/main/java/com/onair/hearit/domain/DomainException.kt
  android/app/src/main/java/com/onair/hearit/domain/DomainExceptionMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/NoBookmarkException.kt
  android/app/src/main/java/com/onair/hearit/domain/UserNotRegisteredException.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: ✨ feat, AN

#371 [AN] fix: android dev-cd 파일 수정
  .github/workflows/android-cd-dev.yml
  .github/workflows/android-cd.yml
Labels: AN, ⚙️ chore, 🎯 release

#378 [AN] refactor: PlaybackService 및 미디어 알림 리팩토링
  android/app/src/main/java/com/onair/hearit/domain/Mapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/PlaybackInfo.kt
  android/app/src/main/java/com/onair/hearit/domain/usecase/GetPlaybackInfoUseCase.kt
  android/app/src/main/java/com/onair/hearit/presentation/BottomPlayerView.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackMediaItemManager.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackService.kt
  android/app/src/main/java/com/onair/hearit/service/PlaybackSessionCallback.kt
  android/app/src/main/java/com/onair/hearit/service/PlayerNotificationManager.kt
Labels: AN, 🔨 refactor

#377 [AN] refactor: 홈, 검색화면 리팩터링
  .github/workflows/android-cd.yml
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/KakaoLoginHelper.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/SearchCategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/SearchRecentFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/result/SearchResultFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashActivity.kt
  android/app/src/main/res/layout/layout_drawer.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: AN, 🔨 refactor

#374 [BE] refactor: 로깅 관련 리팩토링 및 콘솔 로깅 방식 변경 #339
  backend/src/main/java/com/onair/hearit/auth/config/ApiSecurityConfig.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/KakaoLoginRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/LoginRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/SignupRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/request/TokenReissueRequest.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/LoginTokenResponse.java
  backend/src/main/java/com/onair/hearit/auth/dto/response/TokenReissueResponse.java
  backend/src/main/java/com/onair/hearit/auth/infrastructure/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/onair/hearit/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/onair/hearit/common/log/LoggingAspect.java
  backend/src/main/java/com/onair/hearit/common/log/MdcSetupFilter.java
  backend/src/main/java/com/onair/hearit/common/log/RequestLoggingFilter.java
  backend/src/main/java/com/onair/hearit/common/log/config/LogFilterConfig.java
  backend/src/main/java/com/onair/hearit/common/log/config/LogMessageConfig.java
  backend/src/main/java/com/onair/hearit/common/log/dto/ExceptionLog.java
  backend/src/main/java/com/onair/hearit/common/log/dto/RequestInfo.java
  backend/src/main/java/com/onair/hearit/common/log/dto/RequestLog.java
  backend/src/main/java/com/onair/hearit/common/log/dto/ResponseLog.java
  backend/src/main/java/com/onair/hearit/common/log/exception/FilterExceptionLogger.java
  backend/src/main/java/com/onair/hearit/common/log/formatter/ConsoleLogFormatter.java
  backend/src/main/java/com/onair/hearit/common/log/mask/Masking.java
  backend/src/main/java/com/onair/hearit/common/log/mask/MaskingConfig.java
  backend/src/main/java/com/onair/hearit/common/log/mask/MaskingSupport.java
  backend/src/main/java/com/onair/hearit/common/log/mask/MaskingType.java
  backend/src/main/java/com/onair/hearit/common/log/mask/UrlMasker.java
  backend/src/main/java/com/onair/hearit/common/log/mask/strategy/EdgeMaskingStrategy.java
  backend/src/main/java/com/onair/hearit/common/log/mask/strategy/FileUrlMaskingStrategy.java
  backend/src/main/java/com/onair/hearit/common/log/mask/strategy/FullMaskingStrategy.java
  backend/src/main/java/com/onair/hearit/common/log/mask/strategy/MaskingStrategy.java
  backend/src/main/java/com/onair/hearit/common/log/mask/strategy/TokenMaskingStrategy.java
  backend/src/main/java/com/onair/hearit/common/log/message/JsonMaskingPrettyFormatter.java
  backend/src/main/java/com/onair/hearit/dto/response/OriginalAudioResponse.java
  backend/src/main/java/com/onair/hearit/dto/response/ScriptResponse.java
  backend/src/main/java/com/onair/hearit/dto/response/ShortAudioResponse.java
  backend/src/main/resources/log4j2/log4j2.xml
Labels: ✨ feat, BE, 🔨 refactor

#373 [BE] refactor: 도메인 코드 위주의 코드 리팩토링 #354
  backend/src/main/java/com/onair/hearit/admin/application/AdminRecommendHearitService.java
  backend/src/main/java/com/onair/hearit/admin/domain/Admin.java
  backend/src/main/java/com/onair/hearit/application/FixedRecommendedHearitStrategy.java
  backend/src/main/java/com/onair/hearit/application/HearitService.java
  backend/src/main/java/com/onair/hearit/application/KeywordService.java
  backend/src/main/java/com/onair/hearit/application/RecommendHearitStrategy.java
  backend/src/main/java/com/onair/hearit/application/explore/HearitExploreService.java
  backend/src/main/java/com/onair/hearit/auth/domain/RefreshToken.java
  backend/src/main/java/com/onair/hearit/domain/Bookmark.java
  backend/src/main/java/com/onair/hearit/domain/Category.java
  backend/src/main/java/com/onair/hearit/domain/ExploreScore.java
  backend/src/main/java/com/onair/hearit/domain/FileType.java
  backend/src/main/java/com/onair/hearit/domain/FileUrls.java
  backend/src/main/java/com/onair/hearit/domain/Hearit.java
  backend/src/main/java/com/onair/hearit/domain/HearitKeyword.java
  backend/src/main/java/com/onair/hearit/domain/Keyword.java
  backend/src/main/java/com/onair/hearit/domain/Member.java
  backend/src/main/java/com/onair/hearit/domain/RecommendHearit.java
  backend/src/main/java/com/onair/hearit/domain/Source.java
  backend/src/main/java/com/onair/hearit/dto/response/HearitsWithRecommendCategoryResponse.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitKeywordRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/HearitRepository.java
  backend/src/main/java/com/onair/hearit/infrastructure/RecommendHearitRepository.java
  backend/src/main/java/com/onair/hearit/presentation/HearitController.java
  backend/src/test/java/com/onair/hearit/admin/presentation/AdminHearitControllerTest.java
  backend/src/test/java/com/onair/hearit/application/FixedRecommendedHearitStrategyTest.java
  backend/src/test/java/com/onair/hearit/application/HearitExploreServiceTest.java
  backend/src/test/java/com/onair/hearit/application/HearitSearchServiceTest.java
  backend/src/test/java/com/onair/hearit/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/domain/HearitTest.java
  backend/src/test/java/com/onair/hearit/fixture/TestFixture.java
  backend/src/test/java/com/onair/hearit/infrastructure/HearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/infrastructure/RecommendHearitRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/HearitControllerTest.java
Labels: BE, 🔨 refactor

#394 [BE] feat: 내 라이브러리 응답에 Category ColorCode 추가 #391
  backend/src/main/java/com/onair/hearit/application/BookmarkService.java
  backend/src/main/java/com/onair/hearit/application/explore/score/BookmarkScoreFactor.java
  backend/src/main/java/com/onair/hearit/dto/response/BookmarkHearitResponse.java
  backend/src/main/java/com/onair/hearit/infrastructure/BookmarkRepository.java
  backend/src/test/java/com/onair/hearit/infrastructure/BookmarkRepositoryTest.java
  backend/src/test/java/com/onair/hearit/presentation/BookmarkControllerTest.java
Labels: ✨ feat, BE

#396 [BE] feat: 실행 환경 로깅 추가 #395
  backend/src/main/resources/log4j2/log4j2.xml
Labels: ✨ feat, BE

#404 [BE] release: bump version to 1.0.09-SNAPSHOT
  backend/build.gradle
Labels: BE, 🎯 release

#407 [BE] fix: server port 번호 변경 #406
  backend/src/main/resources/application-dev.properties
Labels: BE, 🐞 bug

#410 [BE] fix: swagger 설정에서 서버 내부 포트 80으로 변경 #409
  backend/build.gradle
Labels: BE, 🐞 bug

#408 [BE] release: bump version to 1.0.10-SNAPSHOT
  backend/build.gradle
  backend/src/main/resources/application-dev.properties
Labels: BE, 🐞 bug

#436 [BE] refactor: 히어릿 상세정보에 카테고리 id 추가 #433
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitDetailResponse.java
  backend/src/test/java/com/onair/hearit/app/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
Labels: BE, 🔨 refactor

#431 [AN] fix: auth/check Header 2번 보내는 오류 수정
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/java/com/onair/hearit/HearitApplication.kt
  android/app/src/main/java/com/onair/hearit/data/api/AuthService.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/AuthRemoteDataSource.kt
  android/app/src/main/java/com/onair/hearit/data/datasource/remote/AuthRemoteDataSourceImpl.kt
  android/app/src/main/java/com/onair/hearit/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/onair/hearit/di/RepositoryProvider.kt
  android/app/src/main/java/com/onair/hearit/di/TokenInterceptorProvider.kt
  android/app/src/main/java/com/onair/hearit/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/splash/SplashViewModelFactory.kt
  android/app/whatsnew/whatsnew-ko-KR
Labels: AN, ⛔️ hotfix

#438 [BE] chore: Nginx가 넘겨주는 헤더 ip를 받기 위한 설정 추가 #437
  backend/src/main/resources/application-dev.properties
Labels: BE, 🐞 bug

#442 [BE] refactor: 히어릿 상세 조회 응답에 category color 코드 추가 #441
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitDetailResponse.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
Labels: BE, 🔨 refactor

#419 [BE] Chore : 데이터베이스 스키마 마이그레이션을 위한 Flyway 적용 #405
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/common/domain/HearitKeyword.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/resources/application-fake-test.properties
  backend/src/test/resources/application-integration-test.properties
Labels: BE, ⚙️ chore

#446 [BE] build: bump version to 1.1.0-SNAPSHOT #445
  backend/build.gradle
Labels: BE, ⚙️ chore

#430 [BE] release: 1.1.0
  .github/workflows/backend-prod-cd.yml
  backend/build.gradle
  backend/src/main/java/com/onair/hearit/app/dto/response/ExploredHearitResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitDetailResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitOfCategoryResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitSearchResponse.java
  backend/src/main/java/com/onair/hearit/app/dto/response/HearitsWithRecommendCategoryResponse.java
  backend/src/main/java/com/onair/hearit/common/domain/HearitKeyword.java
  backend/src/main/resources/application-dev.properties
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/main/resources/log4j2/log4j2.xml
  backend/src/test/java/com/onair/hearit/app/application/HearitServiceTest.java
  backend/src/test/java/com/onair/hearit/app/presentation/HearitControllerTest.java
  backend/src/test/resources/application-fake-test.properties
  backend/src/test/resources/application-integration-test.properties
Labels: BE, 🎯 release

#451 [AN] refactor: 카테고리에 따른 북마크 색상 변경 #450
  android/app/src/main/java/com/onair/hearit/data/dto/BookmarkResponse.kt
  android/app/src/main/java/com/onair/hearit/data/mapper/BookmarkMapper.kt
  android/app/src/main/java/com/onair/hearit/domain/model/Bookmark.kt
  android/app/src/main/res/layout/item_bookmark.xml
Labels: AN, 🔨 refactor

#448 [AN] feat: 상세 화면에서 카테고리, 키워드 클릭 시 화면 전환
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/analytics/AnalyticsParamKeys.kt
  android/app/src/main/java/com/onair/hearit/domain/model/SearchInput.kt
  android/app/src/main/java/com/onair/hearit/presentation/DetailResult.kt
  android/app/src/main/java/com/onair/hearit/presentation/Extensions.kt
  android/app/src/main/java/com/onair/hearit/presentation/IntentKeys.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/MainViewModel.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailActivity.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailClickListener.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailKeywordAdapter.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/PlayerDetailKeywordViewHolder.kt
  android/app/src/main/java/com/onair/hearit/presentation/detail/script/ScriptFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/library/LibraryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/SearchFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/category/SearchCategoryFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/search/recent/SearchRecentFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/setting/SettingFragment.kt
  android/app/src/main/res/layout/activity_player_detail.xml
  android/app/src/main/res/layout/fragment_setting.xml
  android/app/src/main/res/layout/item_keyword.xml
  android/app/src/main/res/layout/layout_drawer.xml
  android/app/src/main/res/values/strings.xml
  android/app/whatsnew/whatsnew-ko-KR
Labels: ✨ feat, AN

#456 [BE] chore: prod ci s3 upload 과정 추가
  .github/workflows/backend-prod-ci.yml
Labels: BE, ⚙️ chore

#461 [BE] chore: prod ci s3 upload 과정 제거 #460
  .github/workflows/backend-prod-ci.yml
Labels: BE, ⚙️ chore

#465 [BE] chore: 로그 파일에 port 번호 정보 추가 #463
  backend/src/main/java/com/onair/hearit/log/MdcSetupFilter.java
  backend/src/main/resources/log4j2/log4j2.xml
Labels: BE, ⚙️ chore

#470 [AN] fix: 홈 화면, 탐색 화면 binding NPE 처리
  android/app/build.gradle.kts
  android/app/src/main/java/com/onair/hearit/presentation/explore/ExploreFragment.kt
  android/app/src/main/java/com/onair/hearit/presentation/home/HomeFragment.kt
  android/app/whatsnew/whatsnew-ko-KR
Labels: AN, 🐞 bug

#471 [BE] chore: Manual release&rollback workflow 추가 #462
  .github/workflows/be-manual-release.yml
  .github/workflows/be-manual-rollback.yml
Labels: BE, ⚙️ chore

#481 [AN] refactor: 북마크 주석 처리 #480
  android/app/src/main/java/com/onair/hearit/presentation/explore/ShortsViewHolder.kt
  android/app/src/main/res/layout/item_shorts.xml
Labels: AN, 🔨 refactor
